### ISSUE TITLE
Reference database by UUID

### ISSUE THREAD

**Issue by betodealmeida** [DataJunction/dj#193]

**Comment by samredai** [comment]
@betodealmeida I know you've been looking at this. I've seen something that I think is kind of related to this issue (or at least may be solved by the same solution). With cockroach DB, the `id` column in the generated query is defined using `unique_rowid()`.

*node table*
```sql
CREATE TABLE public.node (
  name VARCHAR NULL,
  created_at TIMESTAMPTZ NULL,
  updated_at TIMESTAMPTZ NULL,
  type public.nodetype NULL,
  id INT8 NOT NULL DEFAULT unique_rowid(),
  description VARCHAR NULL,
  query VARCHAR NULL,
  CONSTRAINT node_pkey PRIMARY KEY (id ASC),
  UNIQUE INDEX node_name_key (name ASC),
  INDEX ix_node_description (description ASC),
  INDEX ix_node_id (id ASC),
  INDEX ix_node_query (query ASC)
)
```

This sets huge numbers as the ID for nodes and databases, for example `804292935094337500`, which causes issues when hitting the API.
```sh
| => curl "http://localhost:8000/metrics/" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   407  100   407    0     0  11305      0 --:--:-- --:--:-- --:--:-- 11305
[
  {
    "id": 804292935094337500,
    "name": "kaggle.num_playtime_events",
    "description": "Number of Steam user playtime events captured",
    "created_at": "2022-10-11T20:45:24.817571+00:00",
    "updated_at": "2022-10-11T20:45:24.817576+00:00",
    "query": "SELECT COUNT(*) FROM kaggle.playtime",
    "dimensions": [
      "kaggle.playtime.amount",
      "kaggle.playtime.behavior",
      "kaggle.playtime.game",
      "kaggle.playtime.user_id",
      "kaggle.playtime.zero"
    ]
  }
]
| => curl "http://localhost:8000/metrics/804292935094337500/sql/?database_id=804292934582501400/" | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   109  100   109    0     0  21800      0 --:--:-- --:--:-- --:--:-- 21800
{
  "detail": [
    {
      "loc": [
        "query",
        "database_id"
      ],
      "msg": "value is not a valid integer",
      "type": "type_error.integer"
    }
  ]
}
```
Would it make more sense to make this field a string and for DJ to take control of setting the UUID instead of leaving it to the database? We could set the field to be unique and then just generate a uuid (i.e. `import uuid; uuid.uuid4().hex`) and then include a single retry for the very rare case where the generated uuid already exists in the database. Let me know what you think.

**Comment by betodealmeida** [comment]
> Would it make more sense to make this field a string and for DJ to take control of setting the UUID instead of leaving it to the database? We could set the field to be unique and then just generate a uuid (i.e. import uuid; uuid.uuid4().hex) and then include a single retry for the very rare case where the generated uuid already exists in the database. Let me know what you think.

SQLAlchemy provides an abstraction when we set the type to UUID — if the database can generate it automatically it will, since it's faster, otherwise it falls back to generating in Python.

I have the PR almost ready, I'll finish it this week.
