### ISSUE TITLE
Add interface for a custom query service

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#342]
We should add an interface between a custom query service and DJ. DJ currently has the `queries` API endpoints which stores queries to the database, runs them, and manages their states. A custom query engine would largely replace this functionality and we need the mechanism to plug one in.

**Checklist**
- [x] Add query service interface to DJ
- [x] Build out djqs to conform to that interface
- [x] Add examples to runbook that demonstrate both working in conjunction

DJ would provide the following:
* `query`: the generated query in ANSI SQL
* `engine`: the query engine to use (Spark, Presto, Druid etc)
* `config`: query-specific config (pulled from `MaterializationConfig`)

A custom query service will provide the following endpoints:

**POST /queries** 

Save query for running
```
{
    "query": "SELECT ...",
    "engine": {
        "name": "spark",
        "version": "2.4.4"
    },
    "config": {}
}
```
Response:
```
{
    "id": "<query_uuid>"
}
```

**POST /queries/<query_uuid>/**

Run query, returns a query execution

Response:
```
{
    "query_uuid": "<query_uuid>",
    "execution_uuid": "<query_execution_uuid>"
}
```

**GET /queries/<query_uuid>/<execution_uuid>/**

Get query execution status.

Response:
```
{
    "query_uuid": "<query_uuid>",
    "execution_uuid": "<query_execution_uuid>",
    "created_at": "<creation_timestamp>",
    "started_at": "<creation_timestamp>",
    "ended_at": "<creation_timestamp>",
    "status": "CREATED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "UNKNOWN",
    "data": {
        "output_table": null | {
            "name": "<table name>",
            "catalog": "<catalog name>",
            "database": "<database name>"
        },
        "direct": null | ...,
        "columns": {
            "<col_name>": "<col_type>"
        }
    }
}
```

**Remaining Questions**
* Should the query engine handle the conversion of ANSI SQL to any selection of dialects? Or should DJ?
* Should the query engine determine whether to save the query to a table or should it allow for a flag to indicate whether to do so?

**Comment by samredai** [comment]
The endpoints look good to me. For the execution response, the `"direct"` attribute isn't clear to me, is that were the data would be if it's directly returned instead of offloaded to an output table? What do you think of changing `"data"` to `"result"` and then `"direct"` to `"data"`? Also I think columns will have to be an ordered array so that it can be applied when the data is returned which will be an array of arrays.
```json
{
    "query_uuid": "<query_uuid>",
    "execution_uuid": "<query_execution_uuid>",
    "created_at": "<creation_timestamp>",
    "started_at": "<creation_timestamp>",
    "ended_at": "<creation_timestamp>",
    "status": "CREATED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "UNKNOWN",
    "results": {
        "output_table": null | {
            "name": "<table name>",
            "catalog": "<catalog name>",
            "database": "<database name>"
        },
        "data": null | [
            [row1],
            [row2],
            ...
        ],
        "columns": [
            {"name": "<col_name>", "type": "<col_type>"}
        ]
    }
}
```

> Should the query engine handle the conversion of ANSI SQL to any selection of dialects? Or should DJ?

My two cents here: Specifically when using a query service, I think DJ should just send the ANSI SQL by default (plus any RAW unprocessed parts) and let the query service handle any conversion to other dialects. Someone running a custom query service could theoretically be using a proprietary query engine with a dialect that's not public. That being said, DJ should guarantee that it preserves the syntax in which the query was defined in the node, i.e. not replacing single quotes with double quotes or anything like that. Maybe we should also have a `"/catalogs/"` endpoint for the query service that lists all available catalogs and the engines that can access them, that way the DJ server could do some validation before submitting the query.

> Should the query engine determine whether to save the query to a table or should it allow for a flag to indicate whether to do so?

The two situations I can think of here are:
1. A client just wants to get the data back, but it's too large to return as json or msgpack
2. A client explicitly wants to get a table name back that it can pass to something else for further processing

For situation 1, I don't know how useful it would be to get a table name when the client (or user) isn't expecting it. I'd like to see how far we can get by caching the data in the query service and using pagination. For situation 2, it feels reasonable to require explicitly asking for storing the results in a table. So how does it sound to have an optional flag for the `POST /queries/<query_uuid>/` endpoint? Maybe something like `?store=true`? The next question in my head is should the request also be able to specify which catalog to store the table in? (I wouldn't go further than that thought, the database and table should definitely be determined by the query service)
