### ISSUE TITLE
Server-Sent Events for running DJ queries

### ISSUE THREAD

**Issue by samredai** [DataJunction/dj#639]
I want to add a way to query DJ for data that uses server sent events but I want to hear thoughts on if this should be optional and if so, how should it be turned on/off.

Query running in DJ has always had an async option but there’s no way to take advantage of it in a UI layer without doing some form of polling for a terminal state (canceled, finished, failed). With an SSE endpoint that’s mono-directional, events are sent to the client over http whenever the query state changes, meaning a UI could just make one request and process the state changes as they stream over (accepted, scheduled, running, etc).

Main questions are:
1. Any reason why we shouldn’t do this?
2. Should it be optional?
3. What should the endpoint be called? (`/stream/` is a common one)
4. How do we handle this in the OSS UI?

For 4 regarding the OSS UI, I think using standard requests works nicely for small data that comes back in less than a few seconds. So I think that should be the default, essentially with async disabled completely. Then I was thinking maybe we can have a global UI setting such as `USE_SSE` which would switch the UI to using the stream endpoint and display the changes to the query state as they’re sent over.

**Comment by shangyian** [comment]
I think we should definitely do this! I delayed adding polling because I suspected we would want this at some point.

I do wonder if instead of having `USE_SSE` as a global setting, this should be enabled on a case-by-case basis for each engine type. For example, the Druid or Postgres engines might not use this, but the Trino or Spark ones would. This can be optionally configured when the DJ server admin adds engines to the system, with some sort of sensible default.

Of course, all of that depends on the actual latency overhead of just using SSE for all requests. If it's not particularly high, then it wouldn't need to be optional and we can just enable it for all engines.

**Comment by agorajek** [comment]
+1 on making this query pattern a setting on the engine. This makes a lot of sense also because the query service setup will vary between user installations.

**Comment by betodealmeida** [comment]
I agree, for context in Superset we have a per-DB async/sync setting. For sub-second DBs like Druid the async overhead is usually bigger than the query response time, so running queries in sync mode is actually faster.

How is the support for SSE these days? I remember a few years ago we wanted an async solution for Preset and we investigated websockets vs SSE, and because SSE requires HTTP 2.0 it wasn't supported in all proxies (IIRC). We ended up using websockets,  but that brings other problems, and SSE seems simpler.

**Comment by cwegener** [comment]
> How is the support for SSE these days?

I don't think SSE has changed much. The main concern is still the same that it is limited to 6 connections per browser. I.e. you could only open a maximum of 6 browser tabs to the same DJ Query Server instance at the same time.

The simplicity of SSE is certainly a big bonus and SSE shouldn't be ruled out simply because of the max number of connections limit.

**Comment by samredai** [comment]
Lots of great input. I'm more familiar with websockets so was initially going to go in that direction, but it has always felt like production environments always have some reason or another why websockets don't "just work" without having to do some workarounds. Could just be my experience but it sounds like it's worth a shot at trying SSE and seeing how far it gets us.
