### ISSUE TITLE
Add custom function that gets substituted with the current temporal partition

### ISSUE THREAD

**Issue by shangyian** [DataJunction/dj#640]
A transform materialization can either happen incrementally or with full replacement. If it gets materialized incrementally, we need the ability to inject the current temporal partition that's being processed into the query. This is useful both in terms of clarity for users as they define their transforms and for cases like the following, where the incrementally processed node requires access to a window defined based on the current temporal partition:
```sql
SELECT
  two.user_id
  SUM(two.clicks) AS clicks_sum
FROM default.some_fact_source two
WHERE two.my_date BETWEEN date_add(<current temporal partition>, -3) AND date_add(<current temporal partition>, 1) 
GROUP BY two.user_id
```

However, instead of using variable substitution, we can add a custom function `CURRENT_TEMPORAL_PARTITION()`. Then the above query would be defined as:
```sql
SELECT
  two.user_id
  SUM(two.clicks) AS clicks_sum
FROM default.some_fact_source two
WHERE two.my_date BETWEEN date_add(CURRENT_TEMPORAL_PARTITION(), -3) AND date_add(CURRENT_TEMPORAL_PARTITION(), 1) 
GROUP BY two.user_id
```

We would substitute a different value for `current_temporal_partition` for each partition that gets processed.

**Comment by agorajek** [comment]
@shangyian let's take this problem apart. The are few ways to achieve this and I think we should have a chat to pick the best one:
1. No special DJ gears: the user uses common DATE_TO_STR/INT udfs and materialization cron settings.
2. Special DJ attributes inside the materialization config. This would mean the DJ modifies the materialization query based on the attributes.
3. Special DJ udfs to make the query "identical" to the materialization query executed by DJ.

**Comment by shangyian** [comment]
A few things we discussed today:

#### The Special UDF
* The special function can be split into two functions, one for date and one for timestamp. We didn't decide on an exact name, but something like `CURRENT_DATE | RUN_DATE | DESIRED_DATE | INTENDED_DATE` could work (and likewise `CURRENT_TS | ...`). Users can use this like `date_add(CURRENT_DATE(), -3)`, which would translate to `date_add(cast(20230706 as date), -3)`.
* Alternatively we can have a setup like `CURRENT_TIME('%Y-%m-%d')`, which would include a format for how the timestamp is intended to be formatted when it's substituted into the query, but this puts more "magic" into the DJ parsing side rather than relying on the user's knowledge of SQL.

#### Conditions on Transforms
* If a special UDF is used anywhere in a transform's query, we'll require that the transform be materialized before it can be used in a downstream query. This means that we would raise an error if we try to build the transform down to its query when no materialization is available.
* If no special UDF is included, there will be no restrictions on how the transform node can be built in downstream queries. 

#### TBD
* What happens when a backfill is scheduled for materialization? Would this mean that we generate the range of `CURRENT_DATE()` values for the backfill and then generate all the backfill queries with the range of values replaced? This seems like a large overhead -- i.e., if we want a 100-day backfill, we'd be generating 100 different queries where the only change is the date.

**Comment by shangyian** [comment]
After some more discussion with @agorajek, we're leaning towards supporting something like `DJ_CURRENT_TIMESTAMP('%Y-%m-%d')` which will return a formatted string of the materialization run's desired timestamp. 

I had a few more notes from thinking through this more. Let me know if one of the two options below is better.

After adding `DJ_CURRENT_TIMESTAMP(...)`, we'll need to check every time we try to build a node whether it has DJ_CURRENT_TIMESTAMP in its query. If it does, that means we can only build a valid query after it's been materialized. We can raise an error in the build when this happens.

One complication is if we try to schedule materialization for a node and it depends on a parent node that needs to be materialized before we can build the query, we would need to kick off a materialization for the parent node first. In my view there are two approaches to this:
  - We enforce an order of operations to when users can set up materializations for their nodes. I'm thinking this might be fine if we return something like
  ```
  Nodes must be materialized in this order:

  "a"    "b"
     \    /
      "c"
        \
        "d"

   You still need to configure materialization for nodes "a" and "b" before you can configure it for "d". 
  ```
  - Instead of enforcing order, we can just assume that nodes will be materialized (once a materialization is successfully set up) to some table that follows a naming pattern like `dj.node.full.name__v1_0`. Then we can always set up materialization but with the expectation that they would be waiting for the upstream tables to materialized before they run.

Thoughts on either option?

**Comment by agorajek** [comment]
@shangyian let me try to summarize what we discussed today:

Assumptions:
- source nodes have availability states monitored by the reflection service
- materialized nodes have the availability states posted by scheduling jobs (through DJ's api). reflection service could be double-checking these availability states (if feasible)
 
Near future:
- when DJ_CURRENT_TIMESTAMP() is used in a query DJ will make sure that node also has materialization config defined.
- when materialization config is CRUD'ed on a node:
  - DJ will build/update its metallization job using the closest materialized parent nodes, and pass them as dependencies to the materialization job.
  - DJ will trigger materialization config refresh on direct downstream nodes, because they should reflect the new upstream materialized entity
- when new (latest) availability state is added to a node, noting major happens, all downstream materialization jobs should already see the new data using their own triggers (e.g. wait for tasks)
- when an older (not latest) availability state is updated on any node (source or otherwise) DJ should send notifications to downstream node owners about the upstream data refreshes. This also asks for a new tab in the node page, say Data Freshness or Data Availability, that would show the available partitions for the current node as well as the partitions that are potentially stale, because some upstream data changed. 

Far future:
- the last point could be extended to automated backfill features but that should not be DJ's focus for now
